### ISSUE TITLE
Required extension "CollisionHook" file("collisionhook.ext") not running

### ISSUE THREAD

**Issue by PATaja** [Mentrillum/Slender-Fortress-Modified-Versions#1]
can you help me ? i don't know how to fix this issue

L 07/02/2020 - 06:42:11: [CLHOOK] Sigscan for PassServerEntityFilter failed - Disabling detour to prevent crashes
L 07/02/2020 - 06:42:11: [SM] Unable to load extension "collisionhook.ext": Unable to hook PassServerEntityFilter!
L 07/02/2020 - 06:42:15: [SM] Unable to load plugin "sf2.smx": Required extension "CollisionHook" file("collisionhook.ext") not running

sry, im still new to this

**Comment by Mentrillum** [comment]
On the wiki is a page on how to set up a SF2 Modified server, I accidentally did not made a addons/sourcemod folder inside of the download. To fix this, drag and drop the extensions folder, gamedata folder, and scripting folder inside of the sourcemod folder found in tf2/tf/addons/sourcemod/. From there you can compile SF2 Modified and have it run easily. Will for sure fix this in the next minutes.

**Comment by PATaja** [comment]
well the collisionhooks is fixed but this happen 

navmesh-test.smx (SP-Readable Navigation Mesh Test): Native "NavMesh_GetAreas" was not found
sf2.smx (Slender Fortress): Could not find required plugin "tf2attributes"

**Comment by Mentrillum** [comment]
Navmesh test isn't required, but you have to get the TF2 Attributes files in their correct order, and all of these folders are within the Sourcemod folder. So tf2attributes.txt goes in the gamedata folder, tf2attributes.inc goes in scripting/include, and both tf2attributes.sp and tf2attributes_example.sp go in the scripting folder. Make sure you compile only tf2attributes.sp, if you're using compile.exe, it'll be found in scripting/compiled, or if you use spcomp.exe, it'll be just above or below the SP folder. Regardless, copy the SMX file and paste it in the plugins folder.

**Comment by PATaja** [comment]
sf2.smx (Slender Fortress): Could not find required plugin "tf2attributes"

im still confuse, i did what you said but still happens.

**Comment by Mentrillum** [comment]
Again, inc folder in sourcemod/scripting/include, both SP files in sourcemod/scripting, txt file in gamedata, compile tf2attributes.sp, place the smx file in sourcemod/plugins. You had to forgot one of these steps. Use compile.exe to compile tf2attributes.sp if you need to if you didn't get an smx file from the SP file, otherwise I can't give you any other solution other than what works.

**Comment by PATaja** [comment]
thx, it fixed man. u can closed this issues
