### ISSUE TITLE
Vscript update curent issues.

### ISSUE THREAD

**Issue by gdfsgdfg** [Mentrillum/Slender-Fortress-Modified-Versions#100]
Bosses won't spawn and for some reason chat was broken I can't tell if the latter is due to some other plugin.

Windows Server.

Edit1: Updated cbasenpc boss spawns, but server still crashed, seems to happen when boss gets near you.

**Comment by Mentrillum** [comment]
Hey there, thank you for reaching out. We are currently aware SF2 has been crashing with CBaseNPC and are waiting for a new build that fixes the crashes to be published. Will announce a new version of SF2M whenever CBaseNPC updates.

**Comment by gdfsgdfg** [comment]
Alright new update, and slender works fine now.
