### ISSUE TITLE
HL2 animations for bosses not working on personal server

### ISSUE THREAD

**Issue by Thervan2** [Mentrillum/Slender-Fortress-Modified-Versions#102]
after creating and setting up my personal sf2 server, i have noticed an issue with animations not playing/recognizing on specific bosses. for example if i have a boss with their custom animations (example : hyper snatcher and grunt), then their animations are working all fine. but then there's something that i've noticed, is that every single boss who happen to have animations coming originally from hl2 (example : paranoia, trypophobia, emily), they all do a t-pose while having their head in a weird angle, for every single animation. and i'm confident that this is an issue with a server, because those animations work just fine on other public servers, but i don't know what could possibly fix it.

image : https://imgur.com/a/yccvsNi

what i found on console : L 12/21/2022 - 10:28:19: [sf2.smx] Boss profile paranoia has been added to the game.
ERROR: Tried to SetParentAttachment for entity info_particle_system (info_particle_system), but it has no attachment named rfoot.
ERROR: Tried to SetParentAttachment for entity info_particle_system (info_particle_system), but it has no attachment named lfoot.
Can't compute incursion distances from the Red spawn room(s). Bots will perform poorly. This is caused by either a missing func_respawnroom, or missing info_player_teamspawn entities within the func_respawnroom.
ERROR: Tried to SetParentAttachment for entity info_particle_system (info_particle_system), but it has no attachment named rfoot.
ERROR: Tried to SetParentAttachment for entity info_particle_system (info_particle_system), but it has no attachment named lfoot.
ERROR: Tried to SetParentAttachment for entity info_particle_system (info_particle_system), but it has no attachment named rfoot.
ERROR: Tried to SetParentAttachment for entity info_particle_system (info_particle_system), but it has no attachment named lfoot.
Can't compute incursion distances from the Red spawn room(s). Bots will perform poorly. This is caused by either a missing func_respawnroom, or missing info_player_teamspawn entities within the func_respawnroom.

**Comment by Mentrillum** [comment]
Some bosses which uses HL2 animations just break randomly and there is no easy fix I can do. Your best bet is to recompile the model and animations model as new models and try that.

**Comment by Thervan2** [comment]
> Some bosses which uses HL2 animations just break randomly and there is no easy fix I can do. Your best bet is to recompile the model and animations model as new models and try that.

yea that was my essential thought of a solution to see if anything would change, and after i recompiled and set up everything, it still is the same. oh well :P

appreciate your answer!
