### ISSUE TITLE
companions's profile within boss profile's cfg won't load

### ISSUE THREAD

**Issue by leo0215** [Mentrillum/Slender-Fortress-Modified-Versions#12]
hello,so I make an boss cfg contain main boss and companions's setting,but when I save and load it,it only scanned main boss and not load companions,I checked log and plugin think there is only main boss in cfg

**Comment by Mentrillum** [comment]
Companion bosses will only load if a profile for that companion boss exists with the main boss in the same pack, if you have the companions in a pack that the main boss isn't in, companions will not spawn.
