### ISSUE TITLE
Help me!

### ISSUE THREAD

**Issue by communisthungary** [Mentrillum/Slender-Fortress-Modified-Versions#122]
When I start my server with SF2M the plugin says this error: sf2.smx (Slender Fortress) : Native "Segment.GetForward" was not found.
What did I do wrong? What file(s) are missing? PLease, help me!

**Comment by JuegosPablo** [comment]
I highly reccomend you update cbasenpc plugin

**Comment by xXxslendermanxXx** [comment]
Try using latest `master` version, it works.
Tested on Windows version of TF2 running on Arch Linux via Proton Experimental

**Comment by communisthungary** [comment]
I have. Nothing seems to work. But to make sure, can you send me the link of the plugin update?

**Comment by communisthungary** [comment]
https://github.com/TF2-DMB/CBaseNPC/releases/tag/1.9.0.102 this is the version I use. I downloaded it on the day it was released.

**Comment by communisthungary** [comment]
L 08/02/2023 - 17:07:33: [CBASENPC] NavMesh: 0xCAAB7A0 NavAreas: 0xF128DD70
L 08/02/2023 - 17:07:33: [CBASENPC] FOUND GAMEDATA OFFSET FOR CBaseEntity::Event_Killed SUCCESSFULLY =| 69
L 08/02/2023 - 17:07:33: [CBASENPC] Registered 644 natives.
L 08/02/2023 - 17:07:33: [CBASENPC] Successfully created & destroyed dummy NPC
L 08/02/2023 - 17:07:34: [SM] Unable to load plugin "sf2.smx": Native "Segment.GetForward" was not found
Here is the console log of the two plugins start up.

**Comment by JuegosPablo** [comment]
you have everything on the date?

**Comment by communisthungary** [comment]
Yeah, I do.

**Comment by JuegosPablo** [comment]
trying swapping the cbasenpc to the version 1.8.5.100 because it seems the last one is kinda bugged (possibly for sourcemod 1.12)

**Comment by communisthungary** [comment]
I'm gonna try it now

**Comment by communisthungary** [comment]
That worked! Thank you so fricking much, man!
