### ISSUE TITLE
sf2.smx error

### ISSUE THREAD

**Issue by Fate970730** [Mentrillum/Slender-Fortress-Modified-Versions#123]
sf2.smx (Slender Fortress): Native "Segment.length.get" was not found

**Comment by gdfsgdfg** [comment]
I fixed that by updating one of the plugins but the problem is the game mode is refusing to start.

**Comment by gdfsgdfg** [comment]
Oh I see why, the game mode refuses to start when the server has more than 32 player slots, that might need fixing.
