### ISSUE TITLE
SF2 Compiling Error.

### ISSUE THREAD

**Issue by TheStyleHedgehog** [Mentrillum/Slender-Fortress-Modified-Versions#134]
Been having some issues with the system that compiles all my scripting files, my sf2.sp just won't compile as it only says "internal error". I don't understand what this means and recently cleaned my files for my Slender Fortress server, any help or ideas?

**Comment by Mentrillum** [comment]
In order to use SM 1.12, you need the SM 1.11 compilers, being spcomp.exe and compile.exe as it is unknown what causes the interal errors for compiling SF2. On the way make sure you also get SM 1.11's handle.inc file and replace the SM 1.12 handle.inc file.

**Comment by Mentrillum** [comment]
You have to update CollisionHooks, via here https://github.com/CookieCat45/CollisionHook/releases/tag/v1.2.0

**Comment by Mentrillum** [comment]
Snag the gamedata link I provided as the extension simply won't load due to outdated gamedata.
