### ISSUE TITLE
Optimization Suggestions

### ISSUE THREAD

**Issue by MAGNAT2645** [Mentrillum/Slender-Fortress-Modified-Versions#14]
You can optimize (a bit) some lines of code:
- If you put macro string (`#define MACRO "TEST"`) in functions, you shouldn't use formatting (`%s`), you should use concatenation (joins strings on compilation time)
For example, [here](https://github.com/Mentrillum/Slender-Fortress-Modified-Versions/blob/master/addons/sourcemod/scripting/sf2.sp#L1655):
```
Format(sBuffer, sizeof(sBuffer), "Slender Fortress (" ... PLUGIN_VERSION_DISPLAY ... ")");
```
but in this case you can just use `strcopy`
```
strcopy(sBuffer, sizeof(sBuffer), "Slender Fortress (" ... PLUGIN_VERSION_DISPLAY ... ")");

// or just use directly (without allocating additional memory for buffer):
Steam_SetGameDescription( "Slender Fortress (" ... PLUGIN_VERSION_DISPLAY ... ")" );
```

- In some cases you should use **[FormatEx](https://www.sourcemod.net/new-api/string/FormatEx)** (read note) instead of typical **Format**
For example, [here](https://github.com/Mentrillum/Slender-Fortress-Modified-Versions/blob/master/addons/sourcemod/scripting/sf2.sp#L2740):
```
FormatEx(sCat, sizeof(sCat), " (copy of %d)", g_iSlenderCopyMaster[i]);
// In this case sCat is not used as input, so we can make this code slightly faster.
```
(just find any line with **Format** native and if output is not used as input - you can replace **Format** with **FormatEx**)

- If you want to check strings for emptiness, you can replace lines like:
```
if ( strlen( buffer ) > 0 )
if ( StrEqual( buffer, "" ) )
```
with
```
if ( buffer[0] != '\0' )
```

- If you want to clear string, you can replace lines like:
```
strcopy( buffer, sizeof buffer, "" );
Format( buffer, sizeof buffer, "" );
```
with
```
buffer[0] = '\0'; // this string is considered empty (even if it has some non-null symbols starting from index 1,2,3 etc.)
```

These little tweaks should slightly speed up code execution.
You can test them with **[Profiler](https://www.sourcemod.net/new-api/profiler/Profiler)** and if they're really faster (than current code) then you should use them.

**Comment by Mentrillum** [comment]
Will take a look into this while developing the next big update, if this works well, I appreciate the suggestion.

**Comment by MAGNAT2645** [comment]
Forgot to tell that you should check [this tutorial](https://forums.alliedmods.net/showthread.php?t=321089#9), especially `Good Coding Practices` section.

**Comment by Mentrillum** [comment]
Because SF2M is VERY expensive, this should help once the next update comes out since beta build 2 looks very pleasing in terms of using some of these methods without me knowing plus my own method, though it will take some time for the final build to come out as I did not expect the update to be big.

**Comment by Mentrillum** [comment]
Added in 1.7.0
