### ISSUE TITLE
[Suggestion] Update SF2_INTRO_DEFAULT_MUSIC

### ISSUE THREAD

**Issue by MAGNAT2645** [Mentrillum/Slender-Fortress-Modified-Versions#16]
`SF2_INTRO_DEFAULT_MUSIC` points to `slender/intro.mp3`
`#define SF2_INTRO_DEFAULT_MUSIC "slender/intro.mp3"`

I couldn't find this file in Required content (this and Kenzzer's repository), there's only `intro_new.mp3`.
Clients are trying to download `intro.mp3` (which doesn't exist in server files, but exists in stringtable `downloadables`) every time they connect. This slowdowns loading time for them.

**Comment by Mentrillum** [comment]
Should be fixed now.

**Comment by MAGNAT2645** [comment]
Yeah. now i see it. But what's the purpose for `intro_new.mp3` then?

**Comment by Mentrillum** [comment]
Ok, so I thought that was the intro sound for the Modified patch but I didn't bother to play it for some reason to check it before I went to release Modified, and this has been unnoticed since the release.
