### ISSUE TITLE
boss spawn, crash.

### ISSUE THREAD

**Issue by PATaja** [Mentrillum/Slender-Fortress-Modified-Versions#2]
hi its me again, i got a problem. when i join my own server, and i collect the page. my game automatically freeze and crash the server when i look the boss. do you know how to fix the problem? thank youu

**Comment by Mentrillum** [comment]
Use the alternative Sourcepawn Navmesh download found here if bosses crash when trying to move https://www.dropbox.com/s/v7a8psuqbpvln22/Sourcepawn%20Navmesh%20Alt.zip?dl=0

**Comment by PATaja** [comment]
omg thank you so much man! :DD it works perfectly

**Comment by Mentrillum** [comment]
See I don't know why you need the alternate download in case bosses crash the server, but whoever made this fix is a legend. Closing issue.
