### ISSUE TITLE
[Suggestion] Add command to reload list of bosses

### ISSUE THREAD

**Issue by some-username-here1** [Mentrillum/Slender-Fortress-Modified-Versions#24]
Currently there's no command or way to reload the list of sf2 bosses without having to either reload the map or plugin itself.
Also it would be really helpful for when adding bosses on the go and testing out if they loaded up just fine or an error is occuring within the profile, individual boss, or boss pack configs

**Comment by Mentrillum** [comment]
I'm trying to figure out a way to where if all bosses don't load, nothing breaks down and the game just runs as if nothing happened, but it'll print out a warning in the logs saying that all bosses didn't load.

**Comment by Mentrillum** [comment]
Impossible to add.
