### ISSUE TITLE
[BUG] Auto-chase sprinters doesn't work as intended.

### ISSUE THREAD

**Issue by SaudDehan04** [Mentrillum/Slender-Fortress-Modified-Versions#25]
Currently, I'm making a boss that is blind / has very little sight (`search_range 150`). I tried using the `fov 0` but it makes the boss bump into players for a few seconds and then chases them which I don't like for the boss to do that, instead I used a very low `search_range` with the `search_alert_gracetime` set to 0 (aka if you get too close to the boss, it chases you immediately). For some reason, Auto-chase sprinters didn't work and I double checked the cfg incase I missed something that breaks it. I tweaked around with the cfg and increased their `search_range` up to their `search_sound_range` (above 1000+) and then reverted the `fov` back to 0, and THEN the auto-chase sprinters worked.

From what I gathered, the auto-chase sprinters mechanic follows the `search_range` instead of `search_sound_range` which I believe is wrong and it was supposed to be the opposite.

**Comment by Mentrillum** [comment]
I am not really sure how auto chase sprinters work in Glub's versions, so I made a guess to where auto chase sprinters is dependent on the boss' search range and not search sound range, if its dependent on the search sound range, I'll make that change in a patch update.

**Comment by SaudDehan04** [comment]
Auto-chase sprinters in Glubbable's works based on sounds. A good example is Terry Akers. He is blind but has very little sight so if people got too close to him he will chases them as well. If anyone sprints around Terry Aker's sound range he will auto chase whoever ran and ignore anyone else that isn't too close to the boss. 

Also, it should make sense: Running makes a ton of noises right? So why would auto-chase sprinters works based on sight for that instead of sound?

**Comment by Mentrillum** [comment]
Issue has been fixed in 1.6.04.
