### ISSUE TITLE
[Bug?] Gamemode no longer changing game description

### ISSUE THREAD

**Issue by some-username-here1** [Mentrillum/Slender-Fortress-Modified-Versions#26]
I'm not sure how, but SF2M is no longer able to change the gamemode description on my server.
Even though two other gamemodes, TF2Ware2 v2.7.6 and PropHunt Redux 3.4.0.0 beta 3,
are able to change it just fine as they're using SteamWorks as well.

**EDIT:** I'm not sure if there's a way to debug this since even the log files aren't saying anything about SF2M failing to change the gamemode. (is there?)

**Comment by Mentrillum** [comment]
I'm not really sure why SteamWorks won't change the game description on your end, Modified servers that use SteamWorks plus my private testing server works fine. Plus if this bug is exclusive to SteamWorks and not SF2M, its not on me as servers with many gamemodes bundled in one server like Freaks n' Slender and the former Dispenz0r's Fun Server didn't have this issue.

**Comment by some-username-here1** [comment]
I don't think it would be considered a bug exclusive to SteamWorks? cause if that was the cause, then the other mentioned plugins would be having issues as well, but it's only happening to SF2M and any other plugin that uses SteamTools instead.

Although it started happening after installing [this plugin](https://forums.alliedmods.net/showthread.php?t=252712)

**Comment by Mentrillum** [comment]
I am unable to replicate this glitch or bug. Every other Modified server that uses either SteamWorks do not have this issue, my only guess is that the plugin you just installed may be the source. And if thats the case, its a bug that I simply cannot fix.

**Comment by Mentrillum** [comment]
External bug, cannot fix.

**Comment by some-username-here1** [comment]
It turns out that TF2ware2 and PropHunt Redux was able to change the game description despite it not working for sf2m, I can try out an older version to see if a change beyond around March 2021 broke the "change gamedesc" code of the plugin?

**Comment by some-username-here1** [comment]
Can I share some snippets of code from the other mentioned plugins, or would that be against a license/rule/etc?
