### ISSUE TITLE
Server automatically closes when any player connects

### ISSUE THREAD

**Issue by FrameLagger** [Mentrillum/Slender-Fortress-Modified-Versions#40]
There is this problem with my server to where I boot up my SF2 server and if anyone tries to connect, it automatically closes the server without giving me any errors on why it keeps crashing/closing.
Does anyone know how to fix this? This just started happening after the update when Valve screwed the game up for a while.

**Comment by FrameLagger** [comment]
Also, Source TV isn't showing boss names in the killfeed/console. Is there a way to fix that too?

**Comment by Mentrillum** [comment]
At the moment, some server hosts are struggling to run SF2, NFOServers for instance could be one of them. Local servers that run on your PC should be fine. It all happened after the Snakewater update. As for SourceTV, sometimes they won't load for the first map. And if changing the map doesn't help, something in the server.cfg is wrong.

**Comment by FrameLagger** [comment]
My server works without the SF2 plugin but doesn't when its on so I'm guessing the latest plugin is now also broken like the rest. As for my SourceTV, all I did in the server.cfg was put in "tv_enable 1" and "name SourceTV". Changing maps will just say "SourceTV is disabled for this server".

**Comment by FrameLagger** [comment]
I don't mind waiting until 1.7.0 to see if that'll fix the issue like the last update problem. Thanks for responding to my issue Mentrillum.

**Comment by FrameLagger** [comment]
lol steamtools had a problem. Its fixed now. Thanks once again Mentrillum for helping me figure this out.
