### ISSUE TITLE
[Suggestion] Slender Bots

### ISSUE THREAD

**Issue by FrameLagger** [Mentrillum/Slender-Fortress-Modified-Versions#41]
Now hear me out, what if there were well functioning bots that collect pages and run away from bosses like actual players?
Also, what if there was a function that can have bots act in different ways like Survival Bots, Page Collecting Bots, Raid Bots, or Boxing Bots? 
I think fully functioning Slender Bots would be a great addition to servers that don't have any players or for people that like playing with bots alone.

**Comment by Mentrillum** [comment]
It is a literal pain to make, no plans are set to make the bots collect pages or do the objectives as of now.
