### ISSUE TITLE
SendDebugMessageToPlayersSpecialRound Compilation Error

### ISSUE THREAD

**Issue by MAGNAT2645** [Mentrillum/Slender-Fortress-Modified-Versions#44]
SF2 1.7.0

If you try to compile it without `DEBUG` the compiler will throw an error:
`undefined symbol "SendDebugMessageToPlayersSpecialRound"` on [this line](https://github.com/Mentrillum/Slender-Fortress-Modified-Versions/blob/master/addons/sourcemod/scripting/sf2.sp#L1557).
So i had to `#include "sf2/debug.sp"` and mark all the stuff in this file as `stock` (since i don't want debug stuff in the smx).

**Comment by MAGNAT2645** [comment]
You can move `SendDebugMessageToPlayersSpecialRound` from debug.sp to some other file.

**Comment by Mentrillum** [comment]
Fixed in 1.7.0.1
