### ISSUE TITLE
Snipers broken in PvP

### ISSUE THREAD

**Issue by KitRifty** [Mentrillum/Slender-Fortress-Modified-Versions#7]
As of 1.5.5.4, the sniper rifles stopped applying damage in PvP. In the update, I saw that the arguments were switched around in [`PvP_GetWeaponCustomDamageType`](https://github.com/Mentrillum/Slender-Fortress-Modified-Versions/blob/88ee8bd00e9f547dbe7044ce48631dcc4d9882c0/addons/sourcemod/scripting/sf2/pvp.sp#L938), and as a result, the call in [`Hook_WeaponGetCustomDamageType`](https://github.com/Mentrillum/Slender-Fortress-Modified-Versions/blob/a0a4e15a0ab58eb7a399065e0ee8b267e8e39150/addons/sourcemod/scripting/sf2.sp#L3721) is passing in the arguments in the wrong order. Swapping the arguments should fix this easily.

**Comment by Mentrillum** [comment]
So while beta testing the new version, I was trying my hardest to find exactly what exactly the problem was when server owners experienced uncommon crashes, and I simply forgot to revert the arguments for PvP_GetWeaponCustomDamageType after finding the crash fix.
