### ISSUE TITLE
Server Crash After 1.5.5.4a

### ISSUE THREAD

**Issue by my3t** [Mentrillum/Slender-Fortress-Modified-Versions#8]
My server crashes as soon as someone joins the server running either 1.5.5.4 or 1.5.5.4a. When I revert it back to 1.5.5.3b, the server runs normally again.

For dhooks, I tried both 2.2.0-detours14 and 2.2.0-detours14a. I also overrode my existing Navmesh and Collision Hook versions to the one shown in the wiki. I updated SteamWorks and Send Proxy Manager.

I was using SourceMod 1.10.0 build 6460 and updated it to build 6492. This didn't solve the problem either. Any clue what could be the cause here?

**Comment by Mentrillum** [comment]
It may have to do with the IsValidClient, IsValidEntity, IsValidEdict, or all of those checks I've put in the commands and Hook_WeaponGetCustomDamageType, or even removals like the CTFPlayer::WantsLagCompensationOnEntity which has now been re-added. The result of this was the cookies weren't precached properly and hitscan weapons not registering properly, even some crashes which still occur. Within hours, or days depending how much more I need to fix for 1.5.5.4b, I'll push out a patch that will revert a lot of these changes to hopefully stop the crashes. For now, might as well wait until I push out a patch update you can try to use.

**Comment by my3t** [comment]
Great, thanks 👍🏻

**Comment by my3t** [comment]
Resolved in 1.5.5.4b.
