### ISSUE TITLE
the server keeps crashing and i have SM.1.10 and all plugins

### ISSUE THREAD

**Issue by SaileLeuhan** [Mentrillum/Slender-Fortress-Modified-Versions#80]
I do not know what I do badly

//SourceMod Batch Compiler
// by the SourceMod Dev Team

//// sf2.sp
//
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\include\entity_prop_stocks.inc(538) : warning 219: local variable "type" shadows a variable at a preceding level
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\include\cbasenpc/entityfactory.inc(130) : error 139: could not find type "GameData"
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\include\cbasenpc/baseentity.inc(365) : error 139: could not find type "DynamicHook"
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\include\cbasenpc/baseentity.inc(365) : error 148: cannot assign null to a non-nullable type
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\include\cbasenpc/baseentity.inc(366) : error 148: cannot assign null to a non-nullable type
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\include\cbasenpc/baseentity.inc(368) : error 116: no methodmap or class was found for DynamicHook
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\include\cbasenpc/baseentity.inc(369) : error 148: cannot assign null to a non-nullable type
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\include\cbasenpc/baseentity.inc(371) : error 104: cannot find any methods for _
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\include\cbasenpc/baseentity.inc(371) : error 017: undefined symbol "Hook_Pre"
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\include\cbasenpc/baseentity.inc(371) : warning 215: expression has no effect
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\include\cbasenpc/baseentity.inc(371) : warning 215: expression has no effect
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\include\cbasenpc/baseentity.inc(371) : error 001: expected token: ";", but found ")"
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\include\cbasenpc/baseentity.inc(371) : fatal error 190: too many error messages on one line
//
// Compilation aborted.
// 10 Errors.
//
// Compilation Time: 6,53 sec
// ----------------------------------------

Press enter to exit ...

**Comment by Mentrillum** [comment]
You need the most up to date DHooks, and make sure you pick up the correct DHooks release build since there is a SM 1.9 and SM 1.10 build.

**Comment by SaileLeuhan** [comment]
I already updated DHooks but when i'm
compiling sf2. says this

//// sf2.sp
//
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\include\entity_prop_stocks.inc(538) : warning 219: local variable "type" shadows a variable at a preceding level
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\include\cbasenpc/entityfactory.inc(130) : error 139: could not find type "GameData"
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\include\morecolors.inc(159) : warning 219: local variable "team" shadows a variable at a preceding level
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\sf2.sp(203) : error 001: expected token: "{", but found "struct"
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\sf2.sp(205) : error 001: expected token: "public", but found "int"
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\sf2.sp(206) : error 001: expected token: "}", but found "int"
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\sf2.sp(208) : error 054: unmatched closing brace ("}")
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\sf2.sp(210) : error 001: expected token: "{", but found "struct"
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\sf2.sp(212) : error 001: expected token: "public", but found "int"
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\sf2.sp(213) : error 001: expected token: "}", but found "int"
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\sf2.sp(222) : error 054: unmatched closing brace ("}")
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\sf2.sp(536) : error 001: expected token: "{", but found "struct"
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\sf2.sp(538) : error 001: expected token: "public", but found "int"
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\sf2.sp(539) : error 001: expected token: "}", but found "char"
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\sf2.sp(541) : error 054: unmatched closing brace ("}")
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\sf2.sp(635) : error 001: expected token: "{", but found "struct"
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\sf2.sp(653) : error 054: unmatched closing brace ("}")
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\sf2.sp(947) : error 139: could not find type "GlobalForward"
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\sf2.sp(948) : error 139: could not find type "GlobalForward"
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\sf2.sp(949) : error 139: could not find type "GlobalForward"
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\sf2.sp(950) : error 139: could not find type "GlobalForward"
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\sf2.sp(951) : error 139: could not find type "GlobalForward"
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\sf2.sp(952) : error 139: could not find type "GlobalForward"
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\sf2.sp(953) : error 139: could not find type "GlobalForward"
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\sf2.sp(954) : error 139: could not find type "GlobalForward"
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\sf2.sp(955) : error 139: could not find type "GlobalForward"
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\sf2.sp(956) : error 139: could not find type "GlobalForward"
// C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\sf2.sp(957) : error 139: could not find type "GlobalForward"
//
// Compilation aborted.
// 26 Errors.
//
// Compilation Time: 7,72 sec
// ----------------------------------------

Press enter to exit ...

**Comment by Mentrillum** [comment]
Ensure the Sourcemod version is 1.10 only, not 1.9 or 1.11 and see what happens.

**Comment by SaileLeuhan** [comment]
FINALLY I was able to compile the sf2.sp file,
I just have some problems on the server:

L 05/13/2022 - 11:39:08: [TF2ITEMS] "GiveNamedItem" offset = 481
L 05/13/2022 - 11:39:10: [SM] Failed to load plugin "csgo_votestart_test.smx": Only runs on CS:GO.
[STEAMTOOLS] Initial loading stage complete...
L 05/13/2022 - 11:39:11: [CBASENPC] FOUND GAMEDATA OFFSET FOR CBaseCombatCharacter::EventKilled SUCCESSFULLY =| 66
L 05/13/2022 - 11:39:11: [SM] Exception reported: Failed to create native "Steam_IsVACEnabled", name is probably already in use
L 05/13/2022 - 11:39:11: [SM] Blaming: swag.smx
L 05/13/2022 - 11:39:11: [SM] Call stack trace:
L 05/13/2022 - 11:39:11: [SM]   [0] CreateNative
L 05/13/2022 - 11:39:11: [SM]   [1] Line 36, C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\swag.sp::AskPluginLoad2
L 05/13/2022 - 11:39:11: [SM] Failed to load plugin "swag.smx": unexpected error 23 in AskPluginLoad callback.
L 05/13/2022 - 11:39:11: [CBASENPC] Successfully created & destroyed dummy NPC
L 05/13/2022 - 11:39:14: [SM] Exception reported: Failed to get CreateInterface
L 05/13/2022 - 11:39:14: [SM] Blaming: dhooks-test.smx
L 05/13/2022 - 11:39:14: [SM] Call stack trace:
L 05/13/2022 - 11:39:14: [SM]   [0] SetFailState
L 05/13/2022 - 11:39:14: [SM]   [1] Line 100, C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\dhooks-test.sp::OnPluginStart
L 05/13/2022 - 11:39:14: [SM] Unable to load plugin "dhooks-test.smx": Error detected in plugin startup (see error logs)
L 05/13/2022 - 11:39:16: [CBASENPC] Installed SF2SpawnPointBaseEntity entity factory
L 05/13/2022 - 11:39:16: [CBASENPC] Installed sf2_game_text entity factory
L 05/13/2022 - 11:39:16: [CBASENPC] Installed sf2_gamerules entity factory
L 05/13/2022 - 11:39:16: [CBASENPC] Installed sf2_trigger_escape entity factory
L 05/13/2022 - 11:39:16: [CBASENPC] Installed sf2_info_player_escapespawn entity factory
L 05/13/2022 - 11:39:16: [CBASENPC] Installed sf2_trigger_pvp entity factory
L 05/13/2022 - 11:39:16: [CBASENPC] Installed sf2_info_player_pvpspawn entity factory
L 05/13/2022 - 11:39:16: [CBASENPC] Installed sf2_info_player_proxyspawn entity factory
L 05/13/2022 - 11:39:16: [CBASENPC] Installed sf2_info_boss_spawn entity factory
L 05/13/2022 - 11:39:16: [CBASENPC] Installed sf2_info_page_spawn entity factory
L 05/13/2022 - 11:39:16: [CBASENPC] Installed sf2_info_page_music entity factory
L 05/13/2022 - 11:39:16: [CBASENPC] Installed sf2_logic_proxy entity factory
L 05/13/2022 - 11:39:16: [CBASENPC] Installed sf2_logic_raid entity factory
L 05/13/2022 - 11:39:16: [CBASENPC] Installed sf2_boss_maker entity factory
L 05/13/2022 - 11:39:16: [CBASENPC] Installed sf2_trigger_boss_despawn entity factory
L 05/13/2022 - 11:39:16: [CBASENPC] Installed sf2_logic_arena entity factory
L 05/13/2022 - 11:39:16: [CBASENPC] Installed sf2_logic_boxing entity factory
L 05/13/2022 - 11:39:16: [CBASENPC] Installed sf2_logic_slaughter entity factory
L 05/13/2022 - 11:39:16: [tf2attributes.smx] Could not initialize call to CEconItem::SetCustomName
L 05/13/2022 - 11:39:16: [SM] Exception reported: Error, can't read file containing the item list : addons\sourcemod\configs\tf2items.weapons.txt
L 05/13/2022 - 11:39:16: [SM] Blaming: tf2items_manager.smx
L 05/13/2022 - 11:39:16: [SM] Call stack trace:
L 05/13/2022 - 11:39:16: [SM]   [0] SetFailState
L 05/13/2022 - 11:39:16: [SM]   [1] Line 261, C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\tf2items_manager.sp::ParseItems
L 05/13/2022 - 11:39:16: [SM]   [2] Line 58, C:\TF2_Server_Manager\Servers\sf2server\Server\tf\addons\sourcemod\scripting\tf2items_manager.sp::OnPluginStart
L 05/13/2022 - 11:39:16: [SM] Unable to load plugin "tf2items_manager.smx": Error detected in plugin startup (see error logs)
L 05/13/2022 - 11:39:16: [votediagnostics.smx] Game: tf

**Comment by SaileLeuhan** [comment]
If dhooks-test.smx and tf2items_manager.smx are fixed, will the server no longer be shut down?

**Comment by SaileLeuhan** [comment]
ok, the server changed the one from "Team Fortress" to "Slender Fortress (1.7.3.3 M)" and also loaded all the npcs and as I said I have SM 1.10 installed and all the other plugins that are required but it still crashes, what else what should i do?

**Comment by SaileLeuhan** [comment]
¿Is it necessary to load something else?

L 05/26/2022 - 19:42:41: [sf2.smx] -------- Mapchange to slender_scp_087_b_v3b -------
L 05/26/2022 - 19:42:41: [sf2.smx] -------- Mapchange to slender_scp_087_b_v3b -------
SetRoundState(0)
L 05/26/2022 - 19:42:41: [sf2.smx] Loading boss profiles from file addons\sourcemod\configs\sf2\profiles.cfg...
L 05/26/2022 - 19:42:41: [sf2.smx] slenderman...
L 05/26/2022 - 19:42:41: [sf2.smx] rake...
L 05/26/2022 - 19:42:41: [sf2.smx] weepingangel...
Error! Variable "$lightwarptexture" is multiply defined in material "models/mentrillum/ahatintime/hypersnatcher/new_snatcher_body"!
L 05/26/2022 - 19:42:41: [sf2.smx] hypersnatcher_nerfed...
L 05/26/2022 - 19:42:41: [sf2.smx] Loaded 4 boss profile(s) from file!
L 05/26/2022 - 19:42:41: [sf2.smx] Loading boss profile files from directory configs/sf2/profiles...
L 05/26/2022 - 19:42:41: [sf2.smx] addons\sourcemod\configs\sf2\profiles does not exist, skipping.
L 05/26/2022 - 19:42:41: [sf2.smx] Reloaded restricted weapons configuration file successfully
L 05/26/2022 - 19:42:41: [sf2.smx] Loaded special rounds file!
L 05/26/2022 - 19:42:41: [sf2.smx] Reloaded class stats configuration file successfully
