### ISSUE TITLE
Need some help.

### ISSUE THREAD

**Issue by TheStyleHedgehog** [Mentrillum/Slender-Fortress-Modified-Versions#81]
Nav's are not working no matter what I try to do to fix it, any advice?

**Comment by Mentrillum** [comment]
A few things could happen. 1, you didn't generate the nav mesh. 2, you did generate the nav mesh but it did not generate on the RED side if at all. 3, the nav mesh file is not in the maps folder, not the download/maps. Or 4, the nav mesh file has nothing. If you are upgrading from the original base_boss method to CBaseNPC, chances are the extension might not have loaded properly. But if its the second reason which is highly likely, I recommend looking at the nav mesh commands so you can manually generate a nav mesh on a pre-existing nav mesh, but ensure this is done on a single player server with cheats on. https://developer.valvesoftware.com/wiki/Nav_Mesh_Commands

**Comment by TheStyleHedgehog** [comment]
I upgraded the CBaseNPC as well as some others, despite everything working the exact same, nav still doesn't work
