### ISSUE TITLE
My sf2 wont load up

### ISSUE THREAD

**Issue by Critical-spec** [Mentrillum/Slender-Fortress-Modified-Versions#82]
my slender fortress 2 couldnt load, i installed plugins and stuff but what else do i need to do?

**Comment by Critical-spec** [comment]
Any body can help me on this? i tried doing sf2_enabled 1 but didnt work and i don't know if i should start the map first or what?

**Comment by mrnoahfink** [comment]
sf2.sp is script, not actually plugin. Complie sf2.sp to create plugin.

**Comment by Critical-spec** [comment]
I compiled it but what else do I need to do

**Comment by mrnoahfink** [comment]
Saw other comments you post. I think only work with 1.10 sourcemod.

**Comment by Critical-spec** [comment]
The dev right?

**Comment by Critical-spec** [comment]
Just hopefully it works when i do the 1.10 sourcemod
lemme just try and see if it works

**Comment by Critical-spec** [comment]
wait which one the stable builds or dev builds please respond

**Comment by mrnoahfink** [comment]
Stable build.

**Comment by Critical-spec** [comment]
sourcemod-1.10.0-git6542-windows, this one right?

**Comment by Critical-spec** [comment]
do you have discord any social medias we can chat on?

**Comment by Critical-spec** [comment]
hm thats weird, I already had the 1.10  stable build is there any solution i need to do?

**Comment by Critical-spec** [comment]
//SourceMod Batch Compiler
// by the SourceMod Dev Team


//// admin-sql-prefetch.sp
// Already compiled.
// ----------------------------------------

//// admin-sql-threaded.sp
// Already compiled.
// ----------------------------------------

//// adminhelp.sp
// Already compiled.
// ----------------------------------------

//// adminmenu.sp
// Already compiled.
// ----------------------------------------

//// anticapslock.sp
//
// anticapslock.sp(29) : error 181: function argument named 'recipients' differs from prototype
//
// 1 Error.
//
// Compilation Time: 0.28 sec
// ----------------------------------------

//// antiflood.sp
// Already compiled.
// ----------------------------------------

//// anyteleporter.sp
// Already compiled.
// ----------------------------------------

//// arena_reloaded.sp
// Already compiled.
// ----------------------------------------

//// auto_steam_update.sp
// Already compiled.
// ----------------------------------------

//// backpack-tf.sp
// Already compiled.
// ----------------------------------------

//// backpack_viewer.sp
// Already compiled.
// ----------------------------------------

//// basebans.sp
// Already compiled.
// ----------------------------------------

//// basechat.sp
// Already compiled.
// ----------------------------------------

//// basecomm.sp
// Already compiled.
// ----------------------------------------

//// basecommands.sp
// Already compiled.
// ----------------------------------------

//// basetriggers.sp
// Already compiled.
// ----------------------------------------

//// basevotes.sp
// Already compiled.
// ----------------------------------------

//// botmanager-names.sp
// Already compiled.
// ----------------------------------------

//// botmanager-randomdifficulty.sp
// Already compiled.
// ----------------------------------------

//// botmanager.sp
// Already compiled.
// ----------------------------------------

//// citybans.sp
//
// citybans.sp(4) : fatal error 183: cannot read from file: "geoipcity"
//
// Compilation aborted.
// 1 Error.
//
// Compilation Time: 0.17 sec
// ----------------------------------------

//// clientprefs.sp
// Already compiled.
// ----------------------------------------

//// connect_method.sp
// Already compiled.
// ----------------------------------------

//// convarfaker.sp
// Already compiled.
// ----------------------------------------

//// csgo_votestart_test.sp
// Already compiled.
// ----------------------------------------

//// custom-chatcolors-clantag.sp
// Already compiled.
// ----------------------------------------

//// custom-chatcolors-distinguish.sp
//
// custom-chatcolors-distinguish.sp(102) : error 001: expected token: "-identifier-", but found ")"
// custom-chatcolors-distinguish.sp(103) : error 029: invalid expression, assumed zero
// custom-chatcolors-distinguish.sp(103) : error 029: invalid expression, assumed zero
// custom-chatcolors-distinguish.sp(103) : error 029: invalid expression, assumed zero
// custom-chatcolors-distinguish.sp(103) : fatal error 190: too many error messages on one line
//
// Compilation aborted.
// 5 Errors.
//
// Compilation Time: 0.25 sec
// ----------------------------------------

//// custom-chatcolors-mysql.sp
// Already compiled.
// ----------------------------------------

//// custom-chatcolors-toggle.sp
// Already compiled.
// ----------------------------------------

//// custom-chatcolors.sp
//
// custom-chatcolors.sp(134) : warning 234: symbol "GetClientAuthString" is marked as deprecated: Use GetClientAuthId
//
//
// custom-chatcolors.sp(200) : error 181: function argument named 'recipients' differs from prototype
//
// 1 Error.
//
// Compilation Time: 0.31 sec
// ----------------------------------------

//// data-keyvalues.sp
//
// data-keyvalues.sp(162) : error 139: could not find type "NativeVotesType"
// data-keyvalues.sp(204) : error 139: could not find type "NativeVote"
// data-keyvalues.sp(307) : warning 203: symbol is never used: "Data_CloseVote"
// data-keyvalues.sp(298) : warning 203: symbol is never used: "Data_RemoveAllItems"
// data-keyvalues.sp(281) : warning 203: symbol is never used: "Data_RemoveItem"
// data-keyvalues.sp(259) : warning 203: symbol is never used: "Data_InsertItem"
// data-keyvalues.sp(241) : warning 203: symbol is never used: "Data_AddItem"
// data-keyvalues.sp(236) : warning 203: symbol is never used: "Data_GetActions"
// data-keyvalues.sp(204) : warning 203: symbol is never used: "Data_CreateVote"
// data-keyvalues.sp(188) : warning 203: symbol is never used: "Data_SetFlags"
// data-keyvalues.sp(183) : warning 203: symbol is never used: "Data_GetFlags"
// data-keyvalues.sp(175) : warning 203: symbol is never used: "Data_GetResultCallback"
// data-keyvalues.sp(167) : warning 203: symbol is never used: "Data_GetHandler"
// data-keyvalues.sp(162) : warning 203: symbol is never used: "Data_GetType"
// data-keyvalues.sp(157) : warning 203: symbol is never used: "Data_SetTargetSteam"
// data-keyvalues.sp(152) : warning 203: symbol is never used: "Data_GetTargetSteam"
// data-keyvalues.sp(147) : warning 203: symbol is never used: "Data_SetTarget"
// data-keyvalues.sp(142) : warning 203: symbol is never used: "Data_GetTarget"
// data-keyvalues.sp(137) : warning 203: symbol is never used: "Data_SetTitle"
// data-keyvalues.sp(127) : warning 203: symbol is never used: "Data_GetTitle"
// data-keyvalues.sp(122) : warning 203: symbol is never used: "Data_SetDetails"
// data-keyvalues.sp(117) : warning 203: symbol is never used: "Data_GetDetails"
// data-keyvalues.sp(112) : warning 203: symbol is never used: "Data_SetInitiator"
// data-keyvalues.sp(107) : warning 203: symbol is never used: "Data_GetInitiator"
// data-keyvalues.sp(102) : warning 203: symbol is never used: "Data_SetTeam"
// data-keyvalues.sp(97) : warning 203: symbol is never used: "Data_GetTeam"
// data-keyvalues.sp(67) : warning 203: symbol is never used: "Data_GetItemDisplay"
// data-keyvalues.sp(50) : warning 203: symbol is never used: "Data_GetItemCount"
// data-keyvalues.sp(48) : warning 203: symbol is never used: "Data_GetItemInfo"
//
// 2 Errors.
//
// Compilation Time: 0.22 sec
// ----------------------------------------

//// dhooks-test.sp
// Already compiled.
// ----------------------------------------

//// endless_ctf.sp
// Already compiled.
// ----------------------------------------

//// enhanced_items.sp
// Already compiled.
// ----------------------------------------

//// funcommands.sp
// Already compiled.
// ----------------------------------------

//// funvotes.sp
// Already compiled.
// ----------------------------------------

//// game.sp
//
// game.sp(420) : error 139: could not find type "NativeVotesKickType"
// game.sp(470) : error 017: undefined symbol "FindEntityByClassname"
// game.sp(523) : error 139: could not find type "NativeVotesType"
// game.sp(553) : error 139: could not find type "NativeVotesPassType"
// game.sp(583) : error 139: could not find type "NativeVote"
// game.sp(596) : error 139: could not find type "NativeVote"
// game.sp(636) : error 139: could not find type "NativeVote"
// game.sp(653) : error 139: could not find type "NativeVotesFailType"
// game.sp(685) : error 139: could not find type "NativeVote"
// game.sp(692) : error 139: could not find type "NativeVote"
// game.sp(699) : error 139: could not find type "NativeVotesPassType"
// game.sp(757) : error 139: could not find type "NativeVote"
// game.sp(794) : error 139: could not find type "NativeVotesCallFailType"
// game.sp(822) : error 139: could not find type "NativeVote"
// game.sp(893) : error 139: could not find type "NativeVotesType"
// game.sp(932) : error 017: undefined symbol "g_EngineVersion"
// game.sp(1009) : error 139: could not find type "NativeVotesType"
// game.sp(1022) : error 139: could not find type "NativeVotesType"
// game.sp(1035) : error 139: could not find type "NativeVotesOverride"
// game.sp(1048) : error 139: could not find type "NativeVotesType"
// game.sp(1061) : error 139: could not find type "NativeVotesOverride"
// game.sp(1074) : error 139: could not find type "NativeVotesOverride"
// game.sp(1087) : error 139: could not find type "NativeVotesOverride"
// game.sp(1129) : error 139: could not find type "NativeVotesPassType"
// game.sp(1260) : error 139: could not find type "NativeVotesFailType"
// game.sp(1265) : error 139: could not find type "NativeVotesCallFailType"
//
// Compilation aborted.
// 26 Errors.
//
// Compilation Time: 0.31 sec
// ----------------------------------------

//// humiliationconditions.sp
// Already compiled.
// ----------------------------------------

//// humiliationglow.sp
// Already compiled.
// ----------------------------------------

//// itemserver.sp
//
// itemserver.sp(7) : fatal error 183: cannot read from file: "tf2items_giveweapon"
//
// Compilation aborted.
// 1 Error.
//
// Compilation Time: 0.19 sec
// ----------------------------------------

//// kartify.sp
// Already compiled.
// ----------------------------------------

//// mapchooser.sp
// Already compiled.
// ----------------------------------------

//// mckayupdater.sp
//
// mckayupdater.sp(49) : error 017: undefined symbol "CONVAR_PREFIX"
// mckayupdater.sp(52) : error 017: undefined symbol "CONVAR_PREFIX"
// mckayupdater.sp(53) : error 017: undefined symbol "PLUGIN_VERSION"
// mckayupdater.sp(87) : error 017: undefined symbol "UPDATE_FILE"
// mckayupdater.sp(90) : error 017: undefined symbol "PLUGIN_VERSION"
// mckayupdater.sp(93) : error 017: undefined symbol "PLUGIN_VERSION"
//
// 6 Errors.
//
// Compilation Time: 0.22 sec
// ----------------------------------------

//// motd_text_http.sp
// Already compiled.
// ----------------------------------------

//// mutecheck.sp
// Already compiled.
// ----------------------------------------

//// namechange_fix.sp
// Already compiled.
// ----------------------------------------

//// namelock.sp
// Already compiled.
// ----------------------------------------

//// nativevotes-basecommands.sp
// Already compiled.
// ----------------------------------------

//// nativevotes.sp
// Already compiled.
// ----------------------------------------

//// nativevotes_kickvote_immunity.sp
// Already compiled.
// ----------------------------------------

//// nativevotes_mapchooser.sp
// Already compiled.
// ----------------------------------------

//// nativevotes_nominations.sp
// Already compiled.
// ----------------------------------------

//// nativevotes_rockthevote.sp
// Already compiled.
// ----------------------------------------

//// nativevotes_votemanager_test.sp
// Already compiled.
// ----------------------------------------

//// nativevotes_votetest.sp
// Already compiled.
// ----------------------------------------

//// navmesh-test.sp
//
// navmesh-test.sp(60) : warning 213: tag mismatch
// navmesh-test.sp(92) : warning 213: tag mismatch
// navmesh-test.sp(95) : error 017: undefined symbol "NavMesh_GetAreas"
// navmesh-test.sp(95) : warning 213: tag mismatch
// navmesh-test.sp(96) : error 017: undefined symbol "NavMeshArea_ID"
// navmesh-test.sp(118) : error 017: undefined symbol "NavMesh_GetAreas"
// navmesh-test.sp(118) : warning 213: tag mismatch
// navmesh-test.sp(140) : warning 213: tag mismatch
// navmesh-test.sp(173) : error 017: undefined symbol "NavMesh_GetAreas"
// navmesh-test.sp(173) : warning 213: tag mismatch
// navmesh-test.sp(192) : warning 213: tag mismatch
// navmesh-test.sp(192) : warning 213: tag mismatch
// navmesh-test.sp(268) : warning 213: tag mismatch
// navmesh-test.sp(296) : error 017: undefined symbol "NavMesh_GetAreas"
// navmesh-test.sp(296) : warning 213: tag mismatch
// navmesh-test.sp(333) : warning 213: tag mismatch
// navmesh-test.sp(334) : warning 213: tag mismatch
// navmesh-test.sp(338) : warning 213: tag mismatch
//
// 5 Errors.
//
// Compilation Time: 0.33 sec
// ----------------------------------------

//// navmesh.sp
// Already compiled.
// ----------------------------------------

//// nextmap.sp
// Already compiled.
// ----------------------------------------

//// nominations.sp
// Already compiled.
// ----------------------------------------

//// no_enemy_in_spawn.sp
// Already compiled.
// ----------------------------------------

//// playercommands.sp
// Already compiled.
// ----------------------------------------

//// player_analytics.sp
//
// player_analytics.sp(7) : fatal error 183: cannot read from file: "geoipcity"
//
// Compilation aborted.
// 1 Error.
//
// Compilation Time: 0.16 sec
// ----------------------------------------

//// rainbowize.sp
//
// rainbowize.sp(186) : error 181: function argument named 'recipients' differs from prototype
//
// 1 Error.
//
// Compilation Time: 0.28 sec
// ----------------------------------------

//// randomcycle.sp
// Already compiled.
// ----------------------------------------

//// really_no_weapons.sp
// Already compiled.
// ----------------------------------------

//// reservedslots.sp
// Already compiled.
// ----------------------------------------

//// rockthevote.sp
// Already compiled.
// ----------------------------------------

//// sf2.sp
// Already compiled.
// ----------------------------------------

//// short_circuit_nerf.sp
// Already compiled.
// ----------------------------------------

//// shutdowncountdown.sp
// Already compiled.
// ----------------------------------------

//// smac_autodemo.sp
//
// smac_autodemo.sp(4) : fatal error 183: cannot read from file: "smac"
//
// Compilation aborted.
// 1 Error.
//
// Compilation Time: 0.16 sec
// ----------------------------------------

//// smdj.sp
//
// smdj.sp(5) : fatal error 183: cannot read from file: "colors"
//
// Compilation aborted.
// 1 Error.
//
// Compilation Time: 0.16 sec
// ----------------------------------------

//// sounds.sp
// Already compiled.
// ----------------------------------------

//// sql-admin-manager.sp
// Already compiled.
// ----------------------------------------

//// steamrep_checker.sp
//
// steamrep_checker.sp(10) : fatal error 183: cannot read from file: "sourcebans"
//
// Compilation aborted.
// 1 Error.
//
// Compilation Time: 0.16 sec
// ----------------------------------------

//// steamtools.sp
// Already compiled.
// ----------------------------------------

//// sticky_jumper_bombz.sp
// Already compiled.
// ----------------------------------------

//// st_gamedesc_override.sp
// Already compiled.
// ----------------------------------------

//// swag.sp
// Already compiled.
// ----------------------------------------

//// teamscores.sp
// Already compiled.
// ----------------------------------------

//// tf2attributes.sp
// Already compiled.
// ----------------------------------------

//// tf2attributes_example.sp
// Already compiled.
// ----------------------------------------

//// tf2items_manager.sp
// Already compiled.
// ----------------------------------------

//// tf_econ_data.sp
//
// tf_econ_data.sp(13) : fatal error 183: cannot read from file: "stocksoup/handles"
//
// Compilation aborted.
// 1 Error.
//
// Compilation Time: 0.23 sec
// ----------------------------------------

//// tidykick.sp
//
// tidykick.sp(5) : fatal error 183: cannot read from file: "connect"
//
// Compilation aborted.
// 1 Error.
//
// Compilation Time: 0.17 sec
// ----------------------------------------

//// unrestricted_fov.sp
//
// unrestricted_fov.sp(6) : fatal error 183: cannot read from file: "easy_commands"
//
// Compilation aborted.
// 1 Error.
//
// Compilation Time: 0.17 sec
// ----------------------------------------

//// votedelay_changelevel.sp
// Already compiled.
// ----------------------------------------

//// votediagnostics.sp
// Already compiled.
// ----------------------------------------

//// votefailed.sp
// Already compiled.
// ----------------------------------------

//// votekick_switcher.sp
// Already compiled.
// ----------------------------------------

//// votescramble.sp
//
// votescramble.sp(122) : error 017: undefined symbol "CPrintToChatAllEx"
// votescramble.sp(159) : warning 234: symbol "FloatDiv" is marked as deprecated: This native is internal implementation. For division use the '/' operator.
//
//
//
// 1 Error.
//
// Compilation Time: 0.31 sec
// ----------------------------------------

Press enter to exit ...

**Comment by Critical-spec** [comment]
u here man @mrnoahfink

**Comment by Critical-spec** [comment]
SF2.SP is compiled now what do i do

**Comment by mrnoahfink** [comment]
Copy from complied folder into plugin folder.

**Comment by mrnoahfink** [comment]
Meanwhile we have discord server to join ~ https://discord.gg/7Zz7RYTCC4

**Comment by Critical-spec** [comment]
Alright I already joined the sf2 before now what’s your user?

**Comment by Critical-spec** [comment]
And also I placed the sf2 compiled folder in plugins now what

**Comment by Critical-spec** [comment]
Wait do I have to put the scripting sf2 folder in plugins right?

**Comment by mrnoahfink** [comment]
Nope! That sp file can stay there

**Comment by Critical-spec** [comment]
Dam alright

**Comment by Critical-spec** [comment]
Just tell me what’s your discord user so we can do this

**Comment by Critical-spec** [comment]
@mrnoahfink respond bro I’m really curious what should I do cause I wanna make my own sf2 server please mann

**Comment by mrnoahfink** [comment]
I’m busy with my life right now. It better off asking help in discord than here tbh.

**Comment by Critical-spec** [comment]
Sorry atleast tell me that before so I couldn’t keep spamming so many times

**Comment by Critical-spec** [comment]
One last thing though which do I need to copy from compile folder? Just the last thing I’m curious about

**Comment by Critical-spec** [comment]
Nvm thx i did it now i was dumb
