### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by TheStyleHedgehog** [Mentrillum/Slender-Fortress-Modified-Versions#90]
Flashlight's don't work and I'm stuck on what to do

**Comment by Mentrillum** [comment]
The beam effect does not work currently but the local light itself should work in the latest patch. If you're blind when the flashlight is on, set r_maxdlights to something other than 0, also r_dynamic should be on.

**Comment by TheStyleHedgehog** [comment]
Alright thanks
